/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.emuladores;

import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Ricardo Guardiola
 */
public class MemoriaFija extends javax.swing.JFrame {
    public double memorySize = 0;
    public double part =0;
    public String parte;
    public double proceso = 0;
    public double ss = 0;
    public double trrr = 0;
    public double var1 = 0;
    public double var2 = 0;
    public double var3 = 0;
    public double var4 = 0;
    public double var5 = 0;
    public double var6 = 0;
    public double var7 = 0;
    public double var8 = 0;
    public int otro = 0;
    /**
     * Creates new form MemoriaFija
     */
    public MemoriaFija() {
        initComponents();
        jtxtMemoria.setText("64");
        jtxtProceso.setText("3");
        
        lblText1.setText("0mb");
        lblText2.setText("0mb"); 
        lblText3.setText("0mb"); 
        lblText4.setText("0mb"); 
        lblText5.setText("0mb"); 
        lblText6.setText("0mb"); 
        lblText7.setText("0mb"); 
        lblText8.setText("0mb");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        barra1 = new javax.swing.JProgressBar();
        jtxtMemoria = new javax.swing.JTextField();
        btnMemoria = new javax.swing.JButton();
        btnProceso = new javax.swing.JButton();
        lblText1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jtxtProceso = new javax.swing.JTextField();
        barra2 = new javax.swing.JProgressBar();
        lblText2 = new javax.swing.JLabel();
        barra3 = new javax.swing.JProgressBar();
        lblText3 = new javax.swing.JLabel();
        barra4 = new javax.swing.JProgressBar();
        lblText4 = new javax.swing.JLabel();
        barra5 = new javax.swing.JProgressBar();
        lblText5 = new javax.swing.JLabel();
        barra6 = new javax.swing.JProgressBar();
        lblText6 = new javax.swing.JLabel();
        barra7 = new javax.swing.JProgressBar();
        lblText7 = new javax.swing.JLabel();
        barra8 = new javax.swing.JProgressBar();
        lblText8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        clear1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        lblText9 = new javax.swing.JLabel();
        barra9 = new javax.swing.JProgressBar();
        barra10 = new javax.swing.JProgressBar();
        lblText10 = new javax.swing.JLabel();
        lblText11 = new javax.swing.JLabel();
        barra11 = new javax.swing.JProgressBar();
        lblText12 = new javax.swing.JLabel();
        barra12 = new javax.swing.JProgressBar();
        lblText13 = new javax.swing.JLabel();
        barra13 = new javax.swing.JProgressBar();
        lblText14 = new javax.swing.JLabel();
        barra14 = new javax.swing.JProgressBar();
        lblText15 = new javax.swing.JLabel();
        barra15 = new javax.swing.JProgressBar();
        lblText16 = new javax.swing.JLabel();
        barra16 = new javax.swing.JProgressBar();
        clear3 = new javax.swing.JButton();
        clear4 = new javax.swing.JButton();
        clear5 = new javax.swing.JButton();
        clear6 = new javax.swing.JButton();
        clear7 = new javax.swing.JButton();
        clear8 = new javax.swing.JButton();
        clear9 = new javax.swing.JButton();
        clear10 = new javax.swing.JButton();
        clear11 = new javax.swing.JButton();
        clear12 = new javax.swing.JButton();
        clear13 = new javax.swing.JButton();
        clear14 = new javax.swing.JButton();
        clear15 = new javax.swing.JButton();
        clear16 = new javax.swing.JButton();
        clear17 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Memoria Fija");

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnMemoria.setText("Cargar");
        btnMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemoriaActionPerformed(evt);
            }
        });

        btnProceso.setText("Cargar");
        btnProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesoActionPerformed(evt);
            }
        });

        lblText1.setText("15mb");
        lblText1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblText1PropertyChange(evt);
            }
        });

        jLabel2.setText("Tamaño de la memoria");

        jtxtProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtProcesoActionPerformed(evt);
            }
        });

        lblText2.setText("15mb");
        lblText2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblText2PropertyChange(evt);
            }
        });

        lblText3.setText("15mb");
        lblText3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblText3PropertyChange(evt);
            }
        });

        lblText4.setText("15mb");
        lblText4.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblText4PropertyChange(evt);
            }
        });

        lblText5.setText("15mb");
        lblText5.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblText5PropertyChange(evt);
            }
        });

        lblText6.setText("15mb");
        lblText6.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblText6PropertyChange(evt);
            }
        });

        lblText7.setText("15mb");
        lblText7.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblText7PropertyChange(evt);
            }
        });

        lblText8.setText("15mb");
        lblText8.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblText8PropertyChange(evt);
            }
        });

        jLabel3.setText("Cargar Proceso");

        clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear1ActionPerformed(evt);
            }
        });

        lblText9.setText("15mb");
        lblText9.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblText9PropertyChange(evt);
            }
        });

        lblText10.setText("15mb");
        lblText10.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblText10PropertyChange(evt);
            }
        });

        lblText11.setText("15mb");
        lblText11.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblText11PropertyChange(evt);
            }
        });

        lblText12.setText("15mb");
        lblText12.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblText12PropertyChange(evt);
            }
        });

        lblText13.setText("15mb");
        lblText13.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblText13PropertyChange(evt);
            }
        });

        lblText14.setText("15mb");
        lblText14.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblText14PropertyChange(evt);
            }
        });

        lblText15.setText("15mb");
        lblText15.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblText15PropertyChange(evt);
            }
        });

        lblText16.setText("15mb");
        lblText16.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblText16PropertyChange(evt);
            }
        });

        clear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear3ActionPerformed(evt);
            }
        });

        clear4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear4ActionPerformed(evt);
            }
        });

        clear5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear5ActionPerformed(evt);
            }
        });

        clear6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear6ActionPerformed(evt);
            }
        });

        clear7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear7ActionPerformed(evt);
            }
        });

        clear8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear8ActionPerformed(evt);
            }
        });

        clear9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear9ActionPerformed(evt);
            }
        });

        clear10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear10ActionPerformed(evt);
            }
        });

        clear11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear11ActionPerformed(evt);
            }
        });

        clear12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear12ActionPerformed(evt);
            }
        });

        clear13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear13ActionPerformed(evt);
            }
        });

        clear14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear14ActionPerformed(evt);
            }
        });

        clear15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear15ActionPerformed(evt);
            }
        });

        clear16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear16ActionPerformed(evt);
            }
        });

        clear17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear17ActionPerformed(evt);
            }
        });

        jLabel4.setText("Participaciones de igual tamaño");

        jLabel5.setText("Particiones de Distinto tamaño");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton2.setText("Limpiar todo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jSeparator1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jtxtMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnMemoria))
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jtxtProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnProceso)))
                                        .addGap(58, 58, 58)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(clear3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(clear4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(clear5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(clear6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(87, 87, 87)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(clear7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(clear8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(barra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblText1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(barra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblText2))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(barra4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblText4))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(barra3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblText3)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(barra5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblText5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(barra6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblText6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(barra7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblText7))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(clear9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(barra8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblText8)))
                        .addGap(43, 43, 43)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(clear13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(clear11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(clear10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(clear15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(clear12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(clear14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(clear17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clear16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(barra11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(barra12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(barra9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(barra10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(barra13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barra14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barra15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barra16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblText11)
                            .addComponent(lblText12)
                            .addComponent(lblText13)
                            .addComponent(lblText15)
                            .addComponent(lblText16)
                            .addComponent(lblText9)
                            .addComponent(lblText10)
                            .addComponent(lblText14)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jSeparator3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(barra1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblText1)
                            .addComponent(clear1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(barra2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblText2))
                            .addComponent(clear3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(barra3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblText3))
                            .addComponent(clear4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(barra4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblText4))
                            .addComponent(clear5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(barra5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblText5))
                            .addComponent(clear6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(barra6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblText6))
                            .addComponent(clear7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clear8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barra7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblText7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barra8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clear9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblText8))
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(clear12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clear13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(clear10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(clear11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(clear14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clear15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(barra9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblText9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(barra10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblText10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblText11)
                                    .addComponent(barra11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(barra12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(lblText12)))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblText13)
                                    .addComponent(barra13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(barra14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblText14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clear16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblText16)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblText15)
                                                .addComponent(barra15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(clear17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(barra16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMemoria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProceso)
                            .addComponent(jtxtProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            //this.setVisible(false);
            Menu menuu = new Menu();
            menuu.setVisible(true);
            dispose();
            
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblText1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblText1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblText1PropertyChange

    private void btnMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemoriaActionPerformed
        memorySize = Double.parseDouble(jtxtMemoria.getText());
        trrr = Double.parseDouble(jtxtMemoria.getText());
        
        part = memorySize/8; 
        //parte = Double.toString(part);
        lblText1.setText(String.format("%.2f",part)+"mb");
        lblText2.setText(String.format("%.2f",part)+"mb");
        lblText3.setText(String.format("%.2f",part)+"mb");
        lblText4.setText(String.format("%.2f",part)+"mb");
        lblText5.setText(String.format("%.2f",part)+"mb");
        lblText6.setText(String.format("%.2f",part)+"mb");
        lblText7.setText(String.format("%.2f",part)+"mb");
        lblText8.setText(String.format("%.2f",part)+"mb");
//        lblText2.setText(parte+"mb"); 
//        lblText3.setText(parte+"mb"); 
//        lblText4.setText(parte+"mb"); 
//        lblText5.setText(parte+"mb"); 
//        lblText6.setText(parte+"mb"); 
//        lblText7.setText(parte+"mb"); 
//        lblText8.setText(parte+"mb"); 
//        
        barra1.setMinimum(0);
        barra1.setMaximum((int)(part*100));
        barra2.setMinimum(0);
        barra2.setMaximum((int)(part*100));
        barra3.setMinimum(0);
        barra3.setMaximum((int)(part*100));
        barra4.setMinimum(0);
        barra4.setMaximum((int)(part*100));
        barra5.setMinimum(0);
        barra5.setMaximum((int)(part*100));
        barra6.setMinimum(0);
        barra6.setMaximum((int)(part*100));
        barra7.setMinimum(0);
        barra7.setMaximum((int)(part*100));
        barra8.setMinimum(0);
        barra8.setMaximum((int)(part*100));
        barra1.setValue(0);
        barra2.setValue(0);
        barra3.setValue(0);
        barra4.setValue(0);
        barra5.setValue(0);
        barra6.setValue(0);
        barra7.setValue(0);
        barra8.setValue(0);
        
        //////////////////////////////////////////////////////////////////
        
        var1 = trrr/2/2/2/2/2;
        var2 = trrr/2/2/2/2/2;
        var3 = trrr/2/2/2/2;
        var4 = trrr/2/2/2;
        var5 = trrr/2/2/2;
        var6 = trrr/2/2/2;
        var7 = trrr/2/2;
        var8 = trrr/2/2;
        
        
        
        lblText9.setText(String.format("%.2f",var1)+"mb");
        lblText10.setText(String.format("%.2f",var2)+"mb");
        lblText11.setText(String.format("%.2f",var3)+"mb");
        lblText12.setText(String.format("%.2f",var4)+"mb");
        lblText13.setText(String.format("%.2f",var5)+"mb");
        lblText14.setText(String.format("%.2f",var6)+"mb");
        lblText15.setText(String.format("%.2f",var7)+"mb");
        lblText16.setText(String.format("%.2f",var8)+"mb");
//        lblText10.setText(String.valueOf(var2));
//        lblText11.setText(String.valueOf(var3));
//        lblText12.setText(String.valueOf(var4));
//        lblText13.setText(String.valueOf(var5));
//        lblText14.setText(String.valueOf(var6));
//        lblText15.setText(String.valueOf(var7));
//        lblText16.setText(String.valueOf(var8));
        
        barra9.setMinimum(0);
        barra10.setMinimum(0);
        barra11.setMinimum(0);
        barra12.setMinimum(0);
        barra13.setMinimum(0);
        barra14.setMinimum(0);
        barra15.setMinimum(0);
        barra16.setMinimum(0);
        barra9.setMaximum((int)(var1));
        barra10.setMaximum((int)(var2));
        barra11.setMaximum((int)(var3));
        barra12.setMaximum((int)(var4));
        barra13.setMaximum((int)(var5));
        barra14.setMaximum((int)(var6));
        barra15.setMaximum((int)(var7));
        barra16.setMaximum((int)(var8));
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMemoriaActionPerformed

    private void lblText2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblText2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblText2PropertyChange

    private void lblText3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblText3PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblText3PropertyChange

    private void lblText4PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblText4PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblText4PropertyChange

    private void lblText5PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblText5PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblText5PropertyChange

    private void lblText6PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblText6PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblText6PropertyChange

    private void lblText7PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblText7PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblText7PropertyChange

    private void lblText8PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblText8PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblText8PropertyChange

    private void btnProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesoActionPerformed
        proceso = Double.parseDouble(jtxtProceso.getText());
        //otro = Integer.parseInt(String.valueOf(proceso));
        
//        if(proceso>part){
//            JOptionPane.showMessageDialog(null, "El proceso debe de tener un tamnio menor", "Error", JOptionPane.ERROR_MESSAGE);
//        }else{
        //barra1.setValue(proceso);
//                if(barra1.getValue()<1){
//                    barra1.setValue(proceso);
//                }else if (barra1.getValue()>0){
//                    barra2.setValue(proceso);
//                }else if(barra2.getValue()>0){
//                    barra3.setValue(proceso);
//                }else if(barra3.getValue()>0){
//                    barra4.setValue(proceso);
//                }else if(barra4.getValue()>0){
//                    barra5.setValue(proceso);
//                }else if(barra5.getValue()>0){
//                    barra6.setValue(proceso);
//                }else if(barra6.getValue()>0){
//                    barra7.setValue(proceso);
//                }else if(barra7.getValue()>0){
//                    barra8.setValue(proceso);
//                }else
//                {}
//
//        if(barra1.getValue()<1){
//        barra1.setValue(proceso);
//        }else if(barra1.getValue()>0){
//            barra2.setValue(proceso);
//        }else if(barra2.getValue()>0){
//            barra3.setValue(proceso);
//        }else if(barra3.getValue()>0){
//            barra4.setValue(proceso);
//        }else if(barra4.getValue()>0){
//            barra5.setValue(proceso);
//        }else if(barra5.getValue()>0){
//            barra6.setValue(proceso);
//           
//        }else if(barra6.getValue()>0){
//            barra7.setValue(proceso);
//        }else if(barra7.getValue()>0){
//            barra8.setValue(proceso);
//            
//        }else if (barra8.getValue()>0){
//            barra1.setValue(proceso);(int)(proceso*100)
//        }else{}

        if(barra9.getValue()==0 && (proceso-1)<barra9.getMaximum()){
            barra9.setValue((int)(proceso*100));
        }else if(barra10.getValue()==0 && (proceso-1)<barra10.getMaximum()){
            barra10.setValue(((int)(proceso*100)));
        }
        else if(barra11.getValue()==0 && (proceso-1)<barra11.getMaximum()){
            barra11.setValue(((int)(proceso*100)));
        }
        else if(barra12.getValue()==0 && (proceso-1)<barra12.getMaximum()){
            barra12.setValue(((int)(proceso*100)));
        }
        else if(barra13.getValue()==0 && (proceso-1)<barra13.getMaximum()){
            barra13.setValue(((int)(proceso*100)));
        }
        else if(barra14.getValue()==0 && (proceso-1)<barra14.getMaximum()){
            barra14.setValue(((int)(proceso*100)));
        }
        else if(barra15.getValue()==0 && (proceso-1)<barra15.getMaximum()){
            barra15.setValue(((int)(proceso*100)));
        }
        else if(barra16.getValue()==0 && (proceso-1)<barra16.getMaximum()){
            barra16.setValue(((int)(proceso*100)));
        }
        
        
        
        if(proceso>part){
        }else{
        if(barra1.getValue()<1){
            barra1.setValue((int)(proceso*100));
        }else if(barra2.getValue()<1){
            barra2.setValue((int)(proceso*100));
        }else if(barra3.getValue()<1){
            barra3.setValue((int)(proceso*100));
        }else if(barra4.getValue()<1){
            barra4.setValue((int)(proceso*100));
        }else if(barra5.getValue()<1){
            barra5.setValue((int)(proceso*100));
        }else if(barra6.getValue()<1){
            barra6.setValue((int)(proceso*100));
        }else if(barra7.getValue()<1){
            barra7.setValue((int)(proceso*100));
        }else if(barra8.getValue()<1){
            barra8.setValue((int)(proceso*100));
        }
        }
        
//        if(barra9.getValue()==0 && proceso<=barra9.getValue()){
//            barra9.setValue((int)(proceso*100));
//        }else if(barra10.getValue()==0 && proceso<barra10.getValue()){
//            barra10.setValue((int)(proceso*100));
//        }else if(barra11.getValue()==0 && proceso<barra11.getValue()){
//            barra11.setValue((int)(proceso*100));
//        }else if(barra12.getValue()==0 && proceso<barra12.getValue()){
//            barra12.setValue((int)(proceso*100));
//        }else if(barra13.getValue()==0 && proceso<barra13.getValue()){
//            barra13.setValue((int)(proceso*100));
//        }else if(barra14.getValue()==0 && proceso<barra14.getValue()){
//            barra14.setValue((int)(proceso*100));
//        }else if(barra15.getValue()==0 && proceso<barra15.getValue()){
//            barra15.setValue((int)(proceso*100));
//        }else if(barra16.getValue()==0 && proceso<barra16.getValue()){
//            barra16.setValue((int)(proceso*100));
//        }
        
        
//        }
        

// TODO add your handling code here:
    }//GEN-LAST:event_btnProcesoActionPerformed

    private void clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear1ActionPerformed
            barra1.setValue(0);
        
            
// TODO add your handling code here:
    }//GEN-LAST:event_clear1ActionPerformed

    private void jtxtProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtProcesoActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtProcesoActionPerformed

    private void lblText9PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblText9PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblText9PropertyChange

    private void lblText10PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblText10PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblText10PropertyChange

    private void lblText11PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblText11PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblText11PropertyChange

    private void lblText12PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblText12PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblText12PropertyChange

    private void lblText13PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblText13PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblText13PropertyChange

    private void lblText14PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblText14PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblText14PropertyChange

    private void lblText15PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblText15PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblText15PropertyChange

    private void lblText16PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblText16PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblText16PropertyChange

    private void clear3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear3ActionPerformed
            barra2.setValue(0);
    }//GEN-LAST:event_clear3ActionPerformed

    private void clear4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear4ActionPerformed
            barra3.setValue(0);
    }//GEN-LAST:event_clear4ActionPerformed

    private void clear5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear5ActionPerformed
            barra4.setValue(0);
    }//GEN-LAST:event_clear5ActionPerformed

    private void clear6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear6ActionPerformed
            barra5.setValue(0);
    }//GEN-LAST:event_clear6ActionPerformed

    private void clear7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear7ActionPerformed
            barra6.setValue(0);
            
    }//GEN-LAST:event_clear7ActionPerformed

    private void clear8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear8ActionPerformed
        barra7.setValue(0);
    }//GEN-LAST:event_clear8ActionPerformed

    private void clear9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear9ActionPerformed
            barra8.setValue(0);
    }//GEN-LAST:event_clear9ActionPerformed

    private void clear10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear10ActionPerformed
        barra9.setValue(0);
    }//GEN-LAST:event_clear10ActionPerformed

    private void clear11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear11ActionPerformed
        barra10.setValue(0);// TODO add your handling code here:
    }//GEN-LAST:event_clear11ActionPerformed

    private void clear12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear12ActionPerformed
        barra11.setValue(0);// TODO add your handling code here:
    }//GEN-LAST:event_clear12ActionPerformed

    private void clear13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear13ActionPerformed
        barra12.setValue(0);// TODO add your handling code here:
    }//GEN-LAST:event_clear13ActionPerformed

    private void clear14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear14ActionPerformed
        barra13.setValue(0);// TODO add your handling code here:
    }//GEN-LAST:event_clear14ActionPerformed

    private void clear15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear15ActionPerformed
        barra14.setValue(0);// TODO add your handling code here:
    }//GEN-LAST:event_clear15ActionPerformed

    private void clear16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear16ActionPerformed
        barra15.setValue(0);// TODO add your handling code here:
    }//GEN-LAST:event_clear16ActionPerformed

    private void clear17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear17ActionPerformed
        barra16.setValue(0);// TODO add your handling code here:
    }//GEN-LAST:event_clear17ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        barra1.setValue(0);
        barra2.setValue(0);
        barra3.setValue(0);
        barra4.setValue(0);
        barra5.setValue(0);
        barra6.setValue(0);
        barra7.setValue(0);
        barra8.setValue(0);
        barra9.setValue(0);
        barra10.setValue(0);
        barra11.setValue(0);
        barra12.setValue(0);
        barra13.setValue(0);
        barra14.setValue(0);
        barra15.setValue(0);
        barra16.setValue(0);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemoriaFija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemoriaFija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemoriaFija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemoriaFija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemoriaFija().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barra1;
    private javax.swing.JProgressBar barra10;
    private javax.swing.JProgressBar barra11;
    private javax.swing.JProgressBar barra12;
    private javax.swing.JProgressBar barra13;
    private javax.swing.JProgressBar barra14;
    private javax.swing.JProgressBar barra15;
    private javax.swing.JProgressBar barra16;
    private javax.swing.JProgressBar barra2;
    private javax.swing.JProgressBar barra3;
    private javax.swing.JProgressBar barra4;
    private javax.swing.JProgressBar barra5;
    private javax.swing.JProgressBar barra6;
    private javax.swing.JProgressBar barra7;
    private javax.swing.JProgressBar barra8;
    private javax.swing.JProgressBar barra9;
    private javax.swing.JButton btnMemoria;
    private javax.swing.JButton btnProceso;
    private javax.swing.JButton clear1;
    private javax.swing.JButton clear10;
    private javax.swing.JButton clear11;
    private javax.swing.JButton clear12;
    private javax.swing.JButton clear13;
    private javax.swing.JButton clear14;
    private javax.swing.JButton clear15;
    private javax.swing.JButton clear16;
    private javax.swing.JButton clear17;
    private javax.swing.JButton clear3;
    private javax.swing.JButton clear4;
    private javax.swing.JButton clear5;
    private javax.swing.JButton clear6;
    private javax.swing.JButton clear7;
    private javax.swing.JButton clear8;
    private javax.swing.JButton clear9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jtxtMemoria;
    private javax.swing.JTextField jtxtProceso;
    private javax.swing.JLabel lblText1;
    private javax.swing.JLabel lblText10;
    private javax.swing.JLabel lblText11;
    private javax.swing.JLabel lblText12;
    private javax.swing.JLabel lblText13;
    private javax.swing.JLabel lblText14;
    private javax.swing.JLabel lblText15;
    private javax.swing.JLabel lblText16;
    private javax.swing.JLabel lblText2;
    private javax.swing.JLabel lblText3;
    private javax.swing.JLabel lblText4;
    private javax.swing.JLabel lblText5;
    private javax.swing.JLabel lblText6;
    private javax.swing.JLabel lblText7;
    private javax.swing.JLabel lblText8;
    private javax.swing.JLabel lblText9;
    // End of variables declaration//GEN-END:variables
}
