/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.emuladores;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author HTS
 */
public class SistemaColegas extends javax.swing.JFrame {

    /**
     * Creates new form SistemaColegas
     */
    //DECLARACIÓN DE VARIABLES
    int tamanioMemoria;
    int procesoCargar;

    public SistemaColegas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresarMenu = new javax.swing.JButton();
        txtTamanioMemoria = new javax.swing.JTextField();
        btnCargarProceso = new javax.swing.JButton();
        btnLiberarMemoria = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTamanioProceso = new javax.swing.JTextField();
        btnCargarProceso1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblEspacio1 = new javax.swing.JLabel();
        lblEspacio2 = new javax.swing.JLabel();
        lblEspacio3 = new javax.swing.JLabel();
        lblEspacio4 = new javax.swing.JLabel();
        lblEspacio5 = new javax.swing.JLabel();
        lblEspacio6 = new javax.swing.JLabel();
        lblEspacio7 = new javax.swing.JLabel();
        lblEspacio8 = new javax.swing.JLabel();
        lblEspacio9 = new javax.swing.JLabel();
        lblEspacio10 = new javax.swing.JLabel();
        lblEspacio11 = new javax.swing.JLabel();
        lblEspacio12 = new javax.swing.JLabel();
        lblEspacio13 = new javax.swing.JLabel();
        lblEspacio14 = new javax.swing.JLabel();
        lblEspacio15 = new javax.swing.JLabel();
        lblEspacio16 = new javax.swing.JLabel();
        lblEspacio17 = new javax.swing.JLabel();
        lblEspacio18 = new javax.swing.JLabel();
        lblEspacio19 = new javax.swing.JLabel();
        lblEspacio20 = new javax.swing.JLabel();
        lblEspacio21 = new javax.swing.JLabel();
        lblEspacio22 = new javax.swing.JLabel();
        lblEspacio23 = new javax.swing.JLabel();
        lblEspacio24 = new javax.swing.JLabel();
        lblEspacio25 = new javax.swing.JLabel();
        lblEspacio26 = new javax.swing.JLabel();
        lblEspacio27 = new javax.swing.JLabel();
        lblEspacio28 = new javax.swing.JLabel();
        lblEspacio29 = new javax.swing.JLabel();
        lblEspacio30 = new javax.swing.JLabel();
        lblEspacio31 = new javax.swing.JLabel();
        lbl32_1 = new javax.swing.JLabel();
        lbl32_2 = new javax.swing.JLabel();
        lbl32_3 = new javax.swing.JLabel();
        lbl32_4 = new javax.swing.JLabel();
        lbl32_5 = new javax.swing.JLabel();
        lbl32_6 = new javax.swing.JLabel();
        lbl32_7 = new javax.swing.JLabel();
        lbl32_8 = new javax.swing.JLabel();
        lbl32_9 = new javax.swing.JLabel();
        lbl32_10 = new javax.swing.JLabel();
        lbl32_11 = new javax.swing.JLabel();
        lbl32_12 = new javax.swing.JLabel();
        lbl32_13 = new javax.swing.JLabel();
        lbl32_14 = new javax.swing.JLabel();
        lbl32_15 = new javax.swing.JLabel();
        lbl32_16 = new javax.swing.JLabel();
        lbl32_17 = new javax.swing.JLabel();
        lbl32_18 = new javax.swing.JLabel();
        lbl32_19 = new javax.swing.JLabel();
        lbl32_20 = new javax.swing.JLabel();
        lbl32_21 = new javax.swing.JLabel();
        lbl32_22 = new javax.swing.JLabel();
        lbl32_23 = new javax.swing.JLabel();
        lbl32_24 = new javax.swing.JLabel();
        lbl32_25 = new javax.swing.JLabel();
        lbl32_26 = new javax.swing.JLabel();
        lbl32_27 = new javax.swing.JLabel();
        lbl32_28 = new javax.swing.JLabel();
        lbl32_29 = new javax.swing.JLabel();
        lbl32_30 = new javax.swing.JLabel();
        lbl32_31 = new javax.swing.JLabel();
        lbl32_32 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTamanioAsignado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegresarMenu.setLabel("Regresar");
        btnRegresarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMenuActionPerformed(evt);
            }
        });

        btnCargarProceso.setText("Cargar");
        btnCargarProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarProcesoActionPerformed(evt);
            }
        });

        btnLiberarMemoria.setText("LiberarMemoria");
        btnLiberarMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarMemoriaActionPerformed(evt);
            }
        });

        jLabel3.setText("Tamaño de la memoria");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Sistema de Colegas");

        btnCargarProceso1.setText("Asignar");
        btnCargarProceso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarProceso1ActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEspacio1.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio1.setToolTipText("");
        lblEspacio1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio1.setOpaque(true);
        jPanel1.add(lblEspacio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 2, 53));

        lblEspacio2.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio2.setToolTipText("");
        lblEspacio2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio2.setOpaque(true);
        jPanel1.add(lblEspacio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 2, 53));

        lblEspacio3.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio3.setToolTipText("");
        lblEspacio3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio3.setOpaque(true);
        jPanel1.add(lblEspacio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 2, 53));

        lblEspacio4.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio4.setToolTipText("");
        lblEspacio4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio4.setOpaque(true);
        jPanel1.add(lblEspacio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 2, 53));

        lblEspacio5.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio5.setToolTipText("");
        lblEspacio5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio5.setOpaque(true);
        jPanel1.add(lblEspacio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 2, 53));

        lblEspacio6.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio6.setToolTipText("");
        lblEspacio6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio6.setOpaque(true);
        jPanel1.add(lblEspacio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 2, 53));

        lblEspacio7.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio7.setToolTipText("");
        lblEspacio7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio7.setOpaque(true);
        jPanel1.add(lblEspacio7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 2, 53));

        lblEspacio8.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio8.setToolTipText("");
        lblEspacio8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio8.setOpaque(true);
        jPanel1.add(lblEspacio8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 2, 53));

        lblEspacio9.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio9.setToolTipText("");
        lblEspacio9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio9.setOpaque(true);
        jPanel1.add(lblEspacio9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 2, 53));

        lblEspacio10.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio10.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio10.setToolTipText("");
        lblEspacio10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio10.setOpaque(true);
        jPanel1.add(lblEspacio10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 2, 53));

        lblEspacio11.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio11.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio11.setToolTipText("");
        lblEspacio11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio11.setOpaque(true);
        jPanel1.add(lblEspacio11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 2, 53));

        lblEspacio12.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio12.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio12.setToolTipText("");
        lblEspacio12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio12.setOpaque(true);
        jPanel1.add(lblEspacio12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 2, 53));

        lblEspacio13.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio13.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio13.setToolTipText("");
        lblEspacio13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio13.setOpaque(true);
        jPanel1.add(lblEspacio13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 2, 53));

        lblEspacio14.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio14.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio14.setToolTipText("");
        lblEspacio14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio14.setOpaque(true);
        jPanel1.add(lblEspacio14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 2, 53));

        lblEspacio15.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio15.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio15.setToolTipText("");
        lblEspacio15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio15.setOpaque(true);
        jPanel1.add(lblEspacio15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 2, 53));

        lblEspacio16.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio16.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio16.setToolTipText("");
        lblEspacio16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio16.setOpaque(true);
        jPanel1.add(lblEspacio16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 2, 53));

        lblEspacio17.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio17.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio17.setToolTipText("");
        lblEspacio17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio17.setOpaque(true);
        jPanel1.add(lblEspacio17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 2, 53));

        lblEspacio18.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio18.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio18.setToolTipText("");
        lblEspacio18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio18.setOpaque(true);
        jPanel1.add(lblEspacio18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 2, 53));

        lblEspacio19.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio19.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio19.setToolTipText("");
        lblEspacio19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio19.setOpaque(true);
        jPanel1.add(lblEspacio19, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 2, 53));

        lblEspacio20.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio20.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio20.setToolTipText("");
        lblEspacio20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio20.setOpaque(true);
        jPanel1.add(lblEspacio20, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 2, 53));

        lblEspacio21.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio21.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio21.setToolTipText("");
        lblEspacio21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio21.setOpaque(true);
        jPanel1.add(lblEspacio21, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 2, 53));

        lblEspacio22.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio22.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio22.setToolTipText("");
        lblEspacio22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio22.setOpaque(true);
        jPanel1.add(lblEspacio22, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 2, 53));

        lblEspacio23.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio23.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio23.setToolTipText("");
        lblEspacio23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio23.setOpaque(true);
        jPanel1.add(lblEspacio23, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 2, 53));

        lblEspacio24.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio24.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio24.setToolTipText("");
        lblEspacio24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio24.setOpaque(true);
        jPanel1.add(lblEspacio24, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 2, 53));

        lblEspacio25.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio25.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio25.setToolTipText("");
        lblEspacio25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio25.setOpaque(true);
        jPanel1.add(lblEspacio25, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 2, 53));

        lblEspacio26.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio26.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio26.setToolTipText("");
        lblEspacio26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio26.setOpaque(true);
        jPanel1.add(lblEspacio26, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 2, 53));

        lblEspacio27.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio27.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio27.setToolTipText("");
        lblEspacio27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio27.setOpaque(true);
        jPanel1.add(lblEspacio27, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 2, 53));

        lblEspacio28.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio28.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio28.setToolTipText("");
        lblEspacio28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio28.setOpaque(true);
        jPanel1.add(lblEspacio28, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 2, 53));

        lblEspacio29.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio29.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio29.setToolTipText("");
        lblEspacio29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio29.setOpaque(true);
        jPanel1.add(lblEspacio29, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 2, 53));

        lblEspacio30.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio30.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio30.setToolTipText("");
        lblEspacio30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio30.setOpaque(true);
        jPanel1.add(lblEspacio30, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 2, 53));

        lblEspacio31.setBackground(new java.awt.Color(51, 51, 51));
        lblEspacio31.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEspacio31.setToolTipText("");
        lblEspacio31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspacio31.setOpaque(true);
        jPanel1.add(lblEspacio31, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 2, 53));

        lbl32_1.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_1.setToolTipText("");
        lbl32_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_1.setOpaque(true);
        jPanel1.add(lbl32_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 53));

        lbl32_2.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_2.setToolTipText("");
        lbl32_2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_2.setOpaque(true);
        jPanel1.add(lbl32_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 53));

        lbl32_3.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_3.setToolTipText("");
        lbl32_3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_3.setOpaque(true);
        jPanel1.add(lbl32_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 30, 53));

        lbl32_4.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_4.setToolTipText("");
        lbl32_4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_4.setOpaque(true);
        jPanel1.add(lbl32_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 30, 53));

        lbl32_5.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_5.setToolTipText("");
        lbl32_5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_5.setOpaque(true);
        jPanel1.add(lbl32_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 30, 53));

        lbl32_6.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_6.setToolTipText("");
        lbl32_6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_6.setOpaque(true);
        jPanel1.add(lbl32_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 30, 53));

        lbl32_7.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_7.setToolTipText("");
        lbl32_7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_7.setOpaque(true);
        jPanel1.add(lbl32_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 30, 53));

        lbl32_8.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_8.setToolTipText("");
        lbl32_8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_8.setOpaque(true);
        jPanel1.add(lbl32_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 30, 53));

        lbl32_9.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_9.setToolTipText("");
        lbl32_9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_9.setOpaque(true);
        jPanel1.add(lbl32_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 30, 53));

        lbl32_10.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_10.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_10.setToolTipText("");
        lbl32_10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_10.setOpaque(true);
        jPanel1.add(lbl32_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 30, 53));

        lbl32_11.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_11.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_11.setToolTipText("");
        lbl32_11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_11.setOpaque(true);
        jPanel1.add(lbl32_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 30, 53));

        lbl32_12.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_12.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_12.setToolTipText("");
        lbl32_12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_12.setOpaque(true);
        jPanel1.add(lbl32_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 30, 53));

        lbl32_13.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_13.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_13.setToolTipText("");
        lbl32_13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_13.setOpaque(true);
        jPanel1.add(lbl32_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 30, 53));

        lbl32_14.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_14.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_14.setToolTipText("");
        lbl32_14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_14.setOpaque(true);
        jPanel1.add(lbl32_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 30, 53));

        lbl32_15.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_15.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_15.setToolTipText("");
        lbl32_15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_15.setOpaque(true);
        jPanel1.add(lbl32_15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 30, 53));

        lbl32_16.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_16.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_16.setToolTipText("");
        lbl32_16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_16.setOpaque(true);
        jPanel1.add(lbl32_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 30, 53));

        lbl32_17.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_17.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_17.setToolTipText("");
        lbl32_17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_17.setOpaque(true);
        jPanel1.add(lbl32_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 30, 53));

        lbl32_18.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_18.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_18.setToolTipText("");
        lbl32_18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_18.setOpaque(true);
        jPanel1.add(lbl32_18, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 30, 53));

        lbl32_19.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_19.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_19.setToolTipText("");
        lbl32_19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_19.setOpaque(true);
        jPanel1.add(lbl32_19, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 30, 53));

        lbl32_20.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_20.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_20.setToolTipText("");
        lbl32_20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_20.setOpaque(true);
        jPanel1.add(lbl32_20, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 30, 53));

        lbl32_21.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_21.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_21.setToolTipText("");
        lbl32_21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_21.setOpaque(true);
        jPanel1.add(lbl32_21, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 30, 53));

        lbl32_22.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_22.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_22.setToolTipText("");
        lbl32_22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_22.setOpaque(true);
        jPanel1.add(lbl32_22, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 30, 53));

        lbl32_23.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_23.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_23.setToolTipText("");
        lbl32_23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_23.setOpaque(true);
        jPanel1.add(lbl32_23, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 30, 53));

        lbl32_24.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_24.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_24.setToolTipText("");
        lbl32_24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_24.setOpaque(true);
        jPanel1.add(lbl32_24, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 30, 53));

        lbl32_25.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_25.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_25.setToolTipText("");
        lbl32_25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_25.setOpaque(true);
        jPanel1.add(lbl32_25, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 30, 53));

        lbl32_26.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_26.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_26.setToolTipText("");
        lbl32_26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_26.setOpaque(true);
        jPanel1.add(lbl32_26, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 30, 53));

        lbl32_27.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_27.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_27.setToolTipText("");
        lbl32_27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_27.setOpaque(true);
        jPanel1.add(lbl32_27, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 30, 53));

        lbl32_28.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_28.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_28.setToolTipText("");
        lbl32_28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_28.setOpaque(true);
        jPanel1.add(lbl32_28, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 30, 53));

        lbl32_29.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_29.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_29.setToolTipText("");
        lbl32_29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_29.setOpaque(true);
        jPanel1.add(lbl32_29, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 30, 53));

        lbl32_30.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_30.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_30.setToolTipText("");
        lbl32_30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_30.setOpaque(true);
        jPanel1.add(lbl32_30, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 30, 53));

        lbl32_31.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_31.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_31.setToolTipText("");
        lbl32_31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_31.setOpaque(true);
        jPanel1.add(lbl32_31, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 30, 53));

        lbl32_32.setBackground(new java.awt.Color(204, 204, 204));
        lbl32_32.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl32_32.setToolTipText("");
        lbl32_32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl32_32.setOpaque(true);
        jPanel1.add(lbl32_32, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 30, 53));

        jLabel4.setText("Tamaño del proceso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(226, 226, 226))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(btnRegresarMenu)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTamanioMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCargarProceso1)))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTamanioProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCargarProceso)
                                    .addComponent(btnLiberarMemoria)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 37, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTamanioAsignado, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCargarProceso1)
                            .addComponent(txtTamanioMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTamanioProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCargarProceso))
                        .addGap(37, 37, 37)
                        .addComponent(btnRegresarMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnLiberarMemoria)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(lblTamanioAsignado, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenuActionPerformed
        // TODO add your handling code here:
        Menu menuPrincipal = new Menu();
        menuPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresarMenuActionPerformed

    private void btnCargarProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarProcesoActionPerformed
        // TODO add your handling code here:

        procesoCargar = Integer.parseInt(txtTamanioProceso.getText());
        if (procesoCargar > 0 && procesoCargar <= tamanioMemoria) {
            String lbl1 = (lbl32_1.getText());
            String lbl17 = (lbl32_17.getText());
            String lbl9 = (lbl32_17.getText());
            String lbl25 = (lbl32_17.getText());

            String textoProcesoCargar = Integer.toString(procesoCargar);
            if (procesoCargar > (tamanioMemoria / 2)) {

                if ((lbl1 == "")) {

                    lbl32_1.setText(textoProcesoCargar);
                    lblEspacio1.setVisible(false);
                    lblEspacio2.setVisible(false);
                    lblEspacio3.setVisible(false);
                    lblEspacio4.setVisible(false);
                    lblEspacio5.setVisible(false);
                    lblEspacio6.setVisible(false);
                    lblEspacio7.setVisible(false);
                    lblEspacio8.setVisible(false);
                    lblEspacio9.setVisible(false);
                    lblEspacio10.setVisible(false);
                    lblEspacio11.setVisible(false);
                    lblEspacio12.setVisible(false);
                    lblEspacio13.setVisible(false);
                    lblEspacio14.setVisible(false);
                    lblEspacio15.setVisible(false);
                    lblEspacio16.setVisible(false);
                    lblEspacio17.setVisible(false);
                    lblEspacio18.setVisible(false);
                    lblEspacio19.setVisible(false);
                    lblEspacio20.setVisible(false);
                    lblEspacio21.setVisible(false);
                    lblEspacio22.setVisible(false);
                    lblEspacio23.setVisible(false);
                    lblEspacio24.setVisible(false);
                    lblEspacio25.setVisible(false);
                    lblEspacio26.setVisible(false);
                    lblEspacio27.setVisible(false);
                    lblEspacio28.setVisible(false);
                    lblEspacio29.setVisible(false);
                    lblEspacio30.setVisible(false);
                    lblEspacio31.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "No hay espacio suficiente para cargar este proceso.", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } else if (procesoCargar > (tamanioMemoria / 4)) {
                if ((lbl1 == "")) {

                    lbl32_1.setText(textoProcesoCargar);
                    lblEspacio1.setVisible(false);
                    lblEspacio2.setVisible(false);
                    lblEspacio3.setVisible(false);
                    lblEspacio4.setVisible(false);
                    lblEspacio5.setVisible(false);
                    lblEspacio6.setVisible(false);
                    lblEspacio7.setVisible(false);
                    lblEspacio8.setVisible(false);
                    lblEspacio9.setVisible(false);
                    lblEspacio10.setVisible(false);
                    lblEspacio11.setVisible(false);
                    lblEspacio12.setVisible(false);
                    lblEspacio13.setVisible(false);
                    lblEspacio14.setVisible(false);
                    lblEspacio15.setVisible(false);
                    lblEspacio16.setVisible(true);
                    lblEspacio17.setVisible(false);
                    lblEspacio18.setVisible(false);
                    lblEspacio19.setVisible(false);
                    lblEspacio20.setVisible(false);
                    lblEspacio21.setVisible(false);
                    lblEspacio22.setVisible(false);
                    lblEspacio23.setVisible(false);
                    lblEspacio24.setVisible(false);
                    lblEspacio25.setVisible(false);
                    lblEspacio26.setVisible(false);
                    lblEspacio27.setVisible(false);
                    lblEspacio28.setVisible(false);
                    lblEspacio29.setVisible(false);
                    lblEspacio30.setVisible(false);
                    lblEspacio31.setVisible(false);
                } else if ((lbl17 == "")) {

                    lbl32_17.setText(textoProcesoCargar);
                    lblEspacio1.setVisible(false);
                    lblEspacio2.setVisible(false);
                    lblEspacio3.setVisible(false);
                    lblEspacio4.setVisible(false);
                    lblEspacio5.setVisible(false);
                    lblEspacio6.setVisible(false);
                    lblEspacio7.setVisible(false);
                    lblEspacio8.setVisible(false);
                    lblEspacio9.setVisible(false);
                    lblEspacio10.setVisible(false);
                    lblEspacio11.setVisible(false);
                    lblEspacio12.setVisible(false);
                    lblEspacio13.setVisible(false);
                    lblEspacio14.setVisible(false);
                    lblEspacio15.setVisible(false);
                    lblEspacio16.setVisible(true);
                    lblEspacio17.setVisible(false);
                    lblEspacio18.setVisible(false);
                    lblEspacio19.setVisible(false);
                    lblEspacio20.setVisible(false);
                    lblEspacio21.setVisible(false);
                    lblEspacio22.setVisible(false);
                    lblEspacio23.setVisible(false);
                    lblEspacio24.setVisible(false);
                    lblEspacio25.setVisible(false);
                    lblEspacio26.setVisible(false);
                    lblEspacio27.setVisible(false);
                    lblEspacio28.setVisible(false);
                    lblEspacio29.setVisible(false);
                    lblEspacio30.setVisible(false);
                    lblEspacio31.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "No hay espacio suficiente para cargar este proceso.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else if (procesoCargar > (tamanioMemoria / 8)) {
                if ((lbl1 == "")) {

                    lbl32_1.setText(textoProcesoCargar);
                    lblEspacio1.setVisible(false);
                    lblEspacio2.setVisible(false);
                    lblEspacio3.setVisible(false);
                    lblEspacio4.setVisible(false);
                    lblEspacio5.setVisible(false);
                    lblEspacio6.setVisible(false);
                    lblEspacio7.setVisible(false);
                    lblEspacio8.setVisible(true);
                    lblEspacio9.setVisible(false);
                    lblEspacio10.setVisible(false);
                    lblEspacio11.setVisible(false);
                    lblEspacio12.setVisible(false);
                    lblEspacio13.setVisible(false);
                    lblEspacio14.setVisible(false);
                    lblEspacio15.setVisible(false);
                    lblEspacio16.setVisible(true);
                    lblEspacio17.setVisible(false);
                    lblEspacio18.setVisible(false);
                    lblEspacio19.setVisible(false);
                    lblEspacio20.setVisible(false);
                    lblEspacio21.setVisible(false);
                    lblEspacio22.setVisible(false);
                    lblEspacio23.setVisible(false);
                    lblEspacio24.setVisible(false);
                    lblEspacio25.setVisible(false);
                    lblEspacio26.setVisible(false);
                    lblEspacio27.setVisible(false);
                    lblEspacio28.setVisible(false);
                    lblEspacio29.setVisible(false);
                    lblEspacio30.setVisible(false);
                    lblEspacio31.setVisible(false);
                } else if ((lbl9 == "")) {

                    lbl32_9.setText(textoProcesoCargar);
                    lblEspacio1.setVisible(false);
                    lblEspacio2.setVisible(false);
                    lblEspacio3.setVisible(false);
                    lblEspacio4.setVisible(false);
                    lblEspacio5.setVisible(false);
                    lblEspacio6.setVisible(false);
                    lblEspacio7.setVisible(false);
                    lblEspacio8.setVisible(true);
                    lblEspacio9.setVisible(false);
                    lblEspacio10.setVisible(false);
                    lblEspacio11.setVisible(false);
                    lblEspacio12.setVisible(false);
                    lblEspacio13.setVisible(false);
                    lblEspacio14.setVisible(false);
                    lblEspacio15.setVisible(false);
                    lblEspacio16.setVisible(true);
                    lblEspacio17.setVisible(false);
                    lblEspacio18.setVisible(false);
                    lblEspacio19.setVisible(false);
                    lblEspacio20.setVisible(false);
                    lblEspacio21.setVisible(false);
                    lblEspacio22.setVisible(false);
                    lblEspacio23.setVisible(false);
                    lblEspacio24.setVisible(false);
                    lblEspacio25.setVisible(false);
                    lblEspacio26.setVisible(false);
                    lblEspacio27.setVisible(false);
                    lblEspacio28.setVisible(false);
                    lblEspacio29.setVisible(false);
                    lblEspacio30.setVisible(false);
                    lblEspacio31.setVisible(false);
                } else if ((lbl17 == "")) {
                    lbl32_17.setText(textoProcesoCargar);
                    lblEspacio1.setVisible(false);
                    lblEspacio2.setVisible(false);
                    lblEspacio3.setVisible(false);
                    lblEspacio4.setVisible(false);
                    lblEspacio5.setVisible(false);
                    lblEspacio6.setVisible(false);
                    lblEspacio7.setVisible(false);
                    lblEspacio8.setVisible(true);
                    lblEspacio9.setVisible(false);
                    lblEspacio10.setVisible(false);
                    lblEspacio11.setVisible(false);
                    lblEspacio12.setVisible(false);
                    lblEspacio13.setVisible(false);
                    lblEspacio14.setVisible(false);
                    lblEspacio15.setVisible(false);
                    lblEspacio16.setVisible(true);
                    lblEspacio17.setVisible(false);
                    lblEspacio18.setVisible(false);
                    lblEspacio19.setVisible(false);
                    lblEspacio20.setVisible(false);
                    lblEspacio21.setVisible(false);
                    lblEspacio22.setVisible(false);
                    lblEspacio23.setVisible(false);
                    lblEspacio24.setVisible(true);
                    lblEspacio25.setVisible(false);
                    lblEspacio26.setVisible(false);
                    lblEspacio27.setVisible(false);
                    lblEspacio28.setVisible(false);
                    lblEspacio29.setVisible(false);
                    lblEspacio30.setVisible(false);
                    lblEspacio31.setVisible(false);
                    
                } else if ((lbl25 == "")) {
                    lbl32_25.setText(textoProcesoCargar);
                    lblEspacio1.setVisible(false);
                    lblEspacio2.setVisible(false);
                    lblEspacio3.setVisible(false);
                    lblEspacio4.setVisible(false);
                    lblEspacio5.setVisible(false);
                    lblEspacio6.setVisible(false);
                    lblEspacio7.setVisible(false);
                    lblEspacio8.setVisible(true);
                    lblEspacio9.setVisible(false);
                    lblEspacio10.setVisible(false);
                    lblEspacio11.setVisible(false);
                    lblEspacio12.setVisible(false);
                    lblEspacio13.setVisible(false);
                    lblEspacio14.setVisible(false);
                    lblEspacio15.setVisible(false);
                    lblEspacio16.setVisible(true);
                    lblEspacio17.setVisible(false);
                    lblEspacio18.setVisible(false);
                    lblEspacio19.setVisible(false);
                    lblEspacio20.setVisible(false);
                    lblEspacio21.setVisible(false);
                    lblEspacio22.setVisible(false);
                    lblEspacio23.setVisible(false);
                    lblEspacio24.setVisible(true);
                    lblEspacio25.setVisible(false);
                    lblEspacio26.setVisible(false);
                    lblEspacio27.setVisible(false);
                    lblEspacio28.setVisible(false);
                    lblEspacio29.setVisible(false);
                    lblEspacio30.setVisible(false);
                    lblEspacio31.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "No hay espacio suficiente para cargar este proceso.", "Error", JOptionPane.ERROR_MESSAGE);
                }
                
                
            }
            
            
            
            
        } else {
            JOptionPane.showMessageDialog(null, "Excede el temaño de la memoria.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCargarProcesoActionPerformed

    private void btnLiberarMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarMemoriaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnLiberarMemoriaActionPerformed

    private void btnCargarProceso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarProceso1ActionPerformed
        // TODO add your handling code here:
        tamanioMemoria = Integer.parseInt(txtTamanioMemoria.getText());
        lblTamanioAsignado.setText(tamanioMemoria + "KB");
        lblEspacio1.setVisible(false);
        lblEspacio2.setVisible(false);
        lblEspacio3.setVisible(false);
        lblEspacio4.setVisible(false);
        lblEspacio5.setVisible(false);
        lblEspacio6.setVisible(false);
        lblEspacio7.setVisible(false);
        lblEspacio8.setVisible(false);
        lblEspacio9.setVisible(false);
        lblEspacio10.setVisible(false);
        lblEspacio11.setVisible(false);
        lblEspacio12.setVisible(false);
        lblEspacio13.setVisible(false);
        lblEspacio14.setVisible(false);
        lblEspacio15.setVisible(false);
        lblEspacio16.setVisible(false);
        lblEspacio17.setVisible(false);
        lblEspacio18.setVisible(false);
        lblEspacio19.setVisible(false);
        lblEspacio20.setVisible(false);
        lblEspacio21.setVisible(false);
        lblEspacio22.setVisible(false);
        lblEspacio23.setVisible(false);
        lblEspacio24.setVisible(false);
        lblEspacio25.setVisible(false);
        lblEspacio26.setVisible(false);
        lblEspacio27.setVisible(false);
        lblEspacio28.setVisible(false);
        lblEspacio29.setVisible(false);
        lblEspacio30.setVisible(false);
        lblEspacio31.setVisible(false);
    }//GEN-LAST:event_btnCargarProceso1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaColegas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaColegas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaColegas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaColegas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaColegas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarProceso;
    private javax.swing.JButton btnCargarProceso1;
    private javax.swing.JButton btnLiberarMemoria;
    private javax.swing.JButton btnRegresarMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl32_1;
    private javax.swing.JLabel lbl32_10;
    private javax.swing.JLabel lbl32_11;
    private javax.swing.JLabel lbl32_12;
    private javax.swing.JLabel lbl32_13;
    private javax.swing.JLabel lbl32_14;
    private javax.swing.JLabel lbl32_15;
    private javax.swing.JLabel lbl32_16;
    private javax.swing.JLabel lbl32_17;
    private javax.swing.JLabel lbl32_18;
    private javax.swing.JLabel lbl32_19;
    private javax.swing.JLabel lbl32_2;
    private javax.swing.JLabel lbl32_20;
    private javax.swing.JLabel lbl32_21;
    private javax.swing.JLabel lbl32_22;
    private javax.swing.JLabel lbl32_23;
    private javax.swing.JLabel lbl32_24;
    private javax.swing.JLabel lbl32_25;
    private javax.swing.JLabel lbl32_26;
    private javax.swing.JLabel lbl32_27;
    private javax.swing.JLabel lbl32_28;
    private javax.swing.JLabel lbl32_29;
    private javax.swing.JLabel lbl32_3;
    private javax.swing.JLabel lbl32_30;
    private javax.swing.JLabel lbl32_31;
    private javax.swing.JLabel lbl32_32;
    private javax.swing.JLabel lbl32_4;
    private javax.swing.JLabel lbl32_5;
    private javax.swing.JLabel lbl32_6;
    private javax.swing.JLabel lbl32_7;
    private javax.swing.JLabel lbl32_8;
    private javax.swing.JLabel lbl32_9;
    private javax.swing.JLabel lblEspacio1;
    private javax.swing.JLabel lblEspacio10;
    private javax.swing.JLabel lblEspacio11;
    private javax.swing.JLabel lblEspacio12;
    private javax.swing.JLabel lblEspacio13;
    private javax.swing.JLabel lblEspacio14;
    private javax.swing.JLabel lblEspacio15;
    private javax.swing.JLabel lblEspacio16;
    private javax.swing.JLabel lblEspacio17;
    private javax.swing.JLabel lblEspacio18;
    private javax.swing.JLabel lblEspacio19;
    private javax.swing.JLabel lblEspacio2;
    private javax.swing.JLabel lblEspacio20;
    private javax.swing.JLabel lblEspacio21;
    private javax.swing.JLabel lblEspacio22;
    private javax.swing.JLabel lblEspacio23;
    private javax.swing.JLabel lblEspacio24;
    private javax.swing.JLabel lblEspacio25;
    private javax.swing.JLabel lblEspacio26;
    private javax.swing.JLabel lblEspacio27;
    private javax.swing.JLabel lblEspacio28;
    private javax.swing.JLabel lblEspacio29;
    private javax.swing.JLabel lblEspacio3;
    private javax.swing.JLabel lblEspacio30;
    private javax.swing.JLabel lblEspacio31;
    private javax.swing.JLabel lblEspacio4;
    private javax.swing.JLabel lblEspacio5;
    private javax.swing.JLabel lblEspacio6;
    private javax.swing.JLabel lblEspacio7;
    private javax.swing.JLabel lblEspacio8;
    private javax.swing.JLabel lblEspacio9;
    private javax.swing.JLabel lblTamanioAsignado;
    private javax.swing.JTextField txtTamanioMemoria;
    private javax.swing.JTextField txtTamanioProceso;
    // End of variables declaration//GEN-END:variables
}
